# Generated by Django 4.2.3 on 2023-07-27 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0004_todo_user_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('083d60f0-5c71-47fd-b812-378a006858ce'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('083d60f0-5c71-47fd-b812-378a006858ce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
