# Generated by Django 4.2.3 on 2023-07-27 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0005_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8ae2a766-cda3-407b-a032-f7c0bc660802'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8ae2a766-cda3-407b-a032-f7c0bc660802'), editable=False, primary_key=True, serialize=False),
        ),
    ]
