# Generated by Django 4.2.3 on 2023-07-27 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0006_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2583972e-560f-4b6a-918d-b8ac205c3647'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2583972e-560f-4b6a-918d-b8ac205c3647'), editable=False, primary_key=True, serialize=False),
        ),
    ]
